version: "3"
services:
  crowd-vit:
    image: pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime
    container_name: cse327project
    volumes:
      - .:/workspace
    working_dir: /workspace
    # 컨테이너가 계속 실행되도록 설정
    tty: true
    stdin_open: true
    # 컨테이너가 시작할 때 실행할 명령어
    command: bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
