version: "3"
services:
  crowd-vit:
    image: pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime
    container_name: crowd-vit-container
    volumes:
      - .:/workspace
      - ./data:/workspace/data
      - ./models:/workspace/models
      - ./outputs:/workspace/outputs
    working_dir: /workspace
    # GPU 지원은 macOS에서는 사용 불가
    # macOS에서는 NVIDIA GPU 지원이 없으므로 CPU로 실행됩니다
    command: ["tail", "-f", "/dev/null"]
