version: "3"
services:
  crowd-vit:
    image: pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime
    container_name: cse327project
    volumes:
      - .:/workspace
      - ./data:/workspace/data
      - ./models:/workspace/models
      - ./outputs:/workspace/outputs
    working_dir: /workspace
    tty: true
    stdin_open: true
    ports:
      - "5000:5000"
      - "6006:6006"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: bash
    # 공유 메모리 크기 증가
    shm_size: "16gb" # 8GB로 설정 (필요에 따라 조정)
