version: "3"
services:
  crowd-vit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cse327project-mac
    volumes:
      - .:/app
      - ./data:/app/data
      - ./models:/app/models
      - ./outputs:/app/outputs
    working_dir: /app
    tty: true
    stdin_open: true
    ports:
      - "5001:5000" # For web interface
      - "6006:6006" # For TensorBoard
    environment:
      - PYTHONPATH=/app
    shm_size: "12gb" # Shared memory size
    # Note: GPU passthrough is managed by the code, not Docker
    command: bash
