# Model Configuration for CrowdViT Wait Time Prediction

# Model settings
model:
  vit_model: "vit_base_patch16_384" # Vision Transformer model from timm
  pretrained: true # Use pretrained weights
  dropout_rate: 0.1 # Dropout rate for regularization
  use_auxiliary_head: true # Use auxiliary head for people counting

# Loss function settings
loss:
  alpha: 0.7 # Weight for wait time loss
  beta: 0.3 # Weight for people count loss

# Training settings
training:
  learning_rate: 0.0001 # Initial learning rate
  weight_decay: 0.00001 # Weight decay for regularization
  batch_size: 16 # Batch size
  num_epochs: 50 # Maximum number of epochs
  warmup_epochs: 5 # Number of warmup epochs
  early_stopping_patience: 10 # Early stopping patience (epochs)

# Data settings
data:
  dataset: "ShanghaiTech" # Dataset name
  part: "A" # Dataset part
  image_size: [384, 384] # Input image size
  data_dir: "./data/ShanghaiTech" # Data directory
